### ISSUE TITLE
`examples`: `ccall` fails to build with `mtl-2.3.*`

### ISSUE THREAD

**Issue by RyanGlScott** [remiturk/libffi#17]
To reproduce the issue, run the following:

```
$ cabal build ccall --constraint="mtl==2.3.*"
Build profile: -w ghc-9.10.3 -O1
In order, the following will be built (use -v for more details):
 - libffi-examples-0.1 (exe:ccall) (first run)
Preprocessing executable 'ccall' for libffi-examples-0.1...
Building executable 'ccall' for libffi-examples-0.1...
[1 of 1] Compiling Main             ( CCall.hs, /home/ryanglscott/Documents/Hacking/Haskell/ci-maintenance/checkout/remiturk/libffi/dist-newstyle/build/x86_64-linux/ghc-9.10.3/libffi-examples-0.1/x/ccall/build/ccall/ccall-tmp/Main.o ) [Control.Monad.State.Strict package changed]
CCall.hs:74:10: error: [GHC-88464]
    Variable not in scope:
      liftM2
        :: (a0 -> [a0] -> [a0])
           -> Text.Parsec.Prim.ParsecT s0 u0 m0 Char
           -> Text.Parsec.Prim.ParsecT s1 u1 m1 [Char]
           -> Text.Parsec.Prim.ParsecT
                [Char]
                st
                ghc-internal-9.1003.0:GHC.Internal.Data.Functor.Identity.Identity
                String
    Suggested fix:
      Perhaps use one of these:
        ‘liftA2’ (imported from Prelude),
        ‘lift’ (imported from Control.Monad.State.Strict),
        ‘liftA’ (imported from Control.Applicative)
   |
74 | pIdent = liftM2 (:) (char '_' <|> letter) (many $ char '_' <|> alphaNum) <?> "identifier"
   |          ^^^^^^

CCall.hs:77:8: error: [GHC-88464]
    Variable not in scope:
      liftM
        :: (String -> Val)
           -> CharParser st0 a3
           -> Text.Parsec.Prim.ParsecT
                [Char]
                (Map String Val)
                ghc-internal-9.1003.0:GHC.Internal.Data.Functor.Identity.Identity
                Val
    Suggested fix:
      Perhaps use one of these:
        ‘lift’ (imported from Control.Monad.State.Strict),
        ‘liftA’ (imported from Control.Applicative)
   |
77 | pArg = liftM S pRead
   |        ^^^^^

CCall.hs:157:13: error: [GHC-88464]
    Variable not in scope:
      forM_ :: [(String, Val)] -> (([Char], a1) -> IO ()) -> IO a2
    |
157 |             forM_ (Map.toList env) $ \(ident, val) -> putStrLn $ ident ++ " = " ++ show val
    |             ^^^^^

Error: [Cabal-7125]
Failed to build exe:ccall from libffi-examples-0.1.
```

This is because in `mtl-2.3.*`, `Control.Monad.State.Strict` no longer re-exports `Control.Monad`. To fix this, we'll need to tighten up the imports a bit.
